spring:
  application:
    name: recruiter_legend
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/db_users
    username: postgres
    password: postgres
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: info.recruiter.legend@gmail.com
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

app:
  reset-password:
    token-expiration: 3600000  # 1 час в миллисекундах
