spring:
  datasource:
    url: jdbc:sqlite:data/recruiter_legend.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

app:
  reset-password:
    token-expiration: 3600000  # 1 час в миллисекундах
