package com.example.app.domain.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;

@Entity
@Getter
@Setter
public class Profile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Column(name = "middle_name")
    private String middleName;

    private String position;

    @Column(name = "birth_date")
    private LocalDate birthDate;

    private String city;

    @Column(name = "phone_number")
    private String phoneNumber;

    private String email;

    @Column(name = "vk_link")
    private String vkLink;

    @Column(name = "telegram_link")
    private String telegramLink;

    @Column(name = "whatsapp_link")
    private String whatsappLink;

    @Lob
    @Column(name = "photo")
    private byte[] photo;

    @Lob
    @Column(name = "resume_file")
    private byte[] resumeFile;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", referencedColumnName = "id")
    private User user;

    // Constructors, getters, and setters are typically generated by Lombok
}
